/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExperimentComparisonChart: typeof import('./../components/ExperimentComparisonChart.vue')['default']
    TyphoonCharts: typeof import('./../components/TyphoonCharts.vue')['default']
    TyphoonGlobe: typeof import('./../components/TyphoonGlobe.vue')['default']
  }
}
